


services:
  postgres:
    image: postgres
    container_name: postgres-db-magalu-ms
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./enviroment-files/database.env
    ports:
      - "5432:5432"
  

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-magalu-ms
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "celery"
    ports:
      - "15672:15672"
      - "5672:5672"
  