apiVersion: v1
kind: Service
metadata:
  name: postgres-db-magalu-ms
  labels:
    app: postgres-db-magalu-ms
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-db-magalu-ms