---
# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-db-magalu-ms
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql


---
#PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-db-magalu-ms
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi