# Generated by Django 5.0.6 on 2024-07-13 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp'), ('PUSH', 'Push')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 20, 12, 41, 657766)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
