# Generated by Django 5.0.6 on 2024-07-17 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 20, 18, 10, 452102)),
        ),
    ]
