name: Pipeline
on: 
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      # Build the Docker image
      - name: Build image Docker
        run: | 
          docker build -t rodrigoferreir/ms-magalu-send-email:${{ github.sha }} ./app/

      #Push the image to DockerHub
      - name: Push the image to DockerHub
        run: |
          docker push rodrigoferreir/ms-magalu-send-email:${{ github.sha }}